
if(!require("arrow")) {install.packages("arrow")}; library(arrow)
if(!require("tidyverse")) {install.packages("tidyverse")}; library(tidyverse)
if(!require("sportyR")) {install.packages("sportyR")}; library(sportyR)
if(!require("gganimate")) {install.packages("gganimate")}; library(gganimate)

library(dplyr)
library(ggplot2)
library(Metrics)
library(kknn)
library(caret)
library(tidyr)
library(mgcv)
library(randomForest)
library(xgboost)
library(showtext)
library(png)
library(tidyverse)
library(gt)

